defaults: &defaults
  host: localhost
  autocreate_indexes: true
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: false
  reconnect_time: 3

development:
  <<: *defaults
  database: dope_development
  autocreate_indexes: true

test:
  <<: *defaults
  database: dope_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: dope_development
